apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
        - name: currency-converter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: OPENEXCHANGERATES_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "currency-converter.fullname" . }}-secret
                  key: OPENEXCHANGERATES_APP_ID

